config/routes.rb
Rails.application.routes.draw do
  devise_scope :email_authentication do
    authenticated :email_authentication do
      root to: "admin#root"
    end

    unauthenticated :email_authentication do
      root to: "devise/sessions#new"
    end
  end

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  concern :sync_routes do
    scope '/patients' do
      get 'sync', to: 'patients#sync_to_user'
      post 'sync', to: 'patients#sync_from_user'
    end

    scope '/blood_pressures' do
      get 'sync', to: 'blood_pressures#sync_to_user'
      post 'sync', to: 'blood_pressures#sync_from_user'
    end

    scope '/blood_sugars' do
      get 'sync', to: 'blood_sugars#sync_to_user'
      post 'sync', to: 'blood_sugars#sync_from_user'
    end

    scope '/prescription_drugs' do
      get 'sync', to: 'prescription_drugs#sync_to_user'
      post 'sync', to: 'prescription_drugs#sync_from_user'
    end

    scope '/facilities' do
      get 'sync', to: 'facilities#sync_to_user'
    end

    scope '/protocols' do
      get 'sync', to: 'protocols#sync_to_user'
    end

    scope '/appointments' do
      get 'sync', to: 'appointments#sync_to_user'
      post 'sync', to: 'appointments#sync_from_user'
    end

    scope '/medical_histories' do
      get 'sync', to: 'medical_histories#sync_to_user'
      post 'sync', to: 'medical_histories#sync_from_user'
    end
  end

  namespace :api, defaults: { format: 'json' } do
    get 'manifest.json', to: 'manifests#show'

    # Returning HTTP Status `410` for deprecated API version `v1`
    namespace :v1 do
      match '*all', via: [:get, :post, :put, :delete, :patch], to: proc { [410, {}, ['']] }
    end

    namespace :v2 do
      get 'ping', to: 'pings#show'
      post 'login', to: 'logins#login_user'

      # Exotel requires all endpoints to be GET
      scope :exotel_call_sessions do
        get 'fetch', to: 'exotel_call_sessions#fetch'
        get 'create', to: 'exotel_call_sessions#create'
        get 'terminate', to: 'exotel_call_sessions#terminate'
      end

      scope :users do
        get 'find', to: 'users#find'
        post 'register', to: 'users#register'
        post '/:id/request_otp', to: 'users#request_otp'
        post '/me/reset_password', to: 'users#reset_password'
      end

      scope '/communications' do
        get 'sync', to: 'communications#sync_to_user'
        post 'sync', to: 'communications#sync_from_user'
      end

      concerns :sync_routes

      resource :help, only: [:show], controller: "help"

      namespace :analytics do
        resource :user_analytics, only: [:show]
      end
    end

    namespace :current, path: 'v3' do
      get 'ping', to: 'pings#show'
      post 'login', to: 'logins#login_user'

      # Exotel requires all endpoints to be GET
      scope :exotel_call_sessions do
        get 'fetch', to: 'exotel_call_sessions#fetch'
        get 'create', to: 'exotel_call_sessions#create'
        get 'terminate', to: 'exotel_call_sessions#terminate'
      end

      resource :twilio_sms_delivery, only: [:create], controller: :twilio_sms_delivery

      scope :users do
        get 'find', to: 'users#find'
        post 'register', to: 'users#register'
        post '/:id/request_otp', to: 'users#request_otp'
        post '/me/reset_password', to: 'users#reset_password'
      end

      concerns :sync_routes

      scope '/encounters' do
        get 'sync', to: 'encounters#sync_to_user'
        post 'sync', to: 'encounters#sync_from_user'

        if FeatureToggle.enabled?('GENERATE_ENCOUNTER_ID_ENDPOINT')
          get 'generate_id', to: 'encounters#generate_id'
        end
      end

      resource :help, only: [:show], controller: "help"

      namespace :analytics do
        resource :user_analytics, only: [:show]
      end
    end
  end

  devise_for :email_authentications,
             path: 'email_authentications',
             controllers: { invitations: 'email_authentications/invitations' }

  resources :admins

  namespace :analytics do
    resources :facilities, only: [:show] do
      get 'graphics', to: 'facilities#whatsapp_graphics'
      get 'patient_list', to: 'facilities#patient_list'
      get 'share', to: 'facilities#share_anonymized_data'
    end

    resources :organizations do
      resources :districts, only: [:show] do
        get 'graphics', to: 'districts#whatsapp_graphics'
        get 'patient_list', to: 'districts#patient_list'
        get 'share', to: 'districts#share_anonymized_data'
      end
    end
  end

  resources :appointments, only: [:index, :update]
  resources :patients, only: [:index, :update]
  resources :organizations, only: [:index], path: 'dashboard'

  scope :my_facilities do
    get '/', to: 'my_facilities#index', as: 'my_facilities_overview'
    get 'ranked_facilities', to: 'my_facilities#ranked_facilities', as: 'my_facilities_ranked_facilities'
    get 'blood_pressure_control', to: 'my_facilities#blood_pressure_control', as: 'my_facilities_blood_pressure_control'
  end

  namespace :admin do
    resources :organizations

    resources :facilities, only: [:index] do
      collection do
        get 'upload'
        post 'upload'
      end
    end
    resources :facility_groups do
      resources :facilities
    end

    resources :protocols do
      resources :protocol_drugs
    end

    resources :users do
      put 'reset_otp', to: 'users#reset_otp'
      put 'disable_access', to: 'users#disable_access'
      put 'enable_access', to: 'users#enable_access'
    end
  end

  if FeatureToggle.enabled?('PURGE_ENDPOINT_FOR_QA')
    namespace :qa do
      delete 'purge', to: 'purges#purge_patient_data'
    end
  end

  authenticate :email_authentication, -> (a) { a.user.has_permission?(:view_sidekiq_ui) } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/admins/_form.html.erb
<% user_permissions = current_admin.user_permissions.pluck(:permission_slug) %>

<%= react_component "InviteAdminForm",
                    admin: admin,
                    email: admin.email,
                    selected_permissions: admin.user_permissions.map { |permission| Permissions::ALL_PERMISSIONS[permission.permission_slug.to_sym] }.uniq,
                    selected_facility_groups: admin.user_permissions.where(resource_type: 'FacilityGroup').map { |permission| { resource_id: permission.resource.id, resource_type: permission.resource_type, resource_name: permission.resource.name } if permission.resource.present? }.compact.uniq,
                    organizations: policy_scope([:manage, :admin, Organization.all]),
                    facility_groups: policy_scope([:manage, :admin, FacilityGroup.all]),
                    facilities: policy_scope([:manage, :admin, Facility.all]),
                    permissions: policy([:manage, :admin, User]).allowed_permissions,
                    access_levels: policy([:manage, :admin, User]).allowed_access_levels,
                    submit_route: admin_path(admin),
                    allow_email_edit: false,
                    submit_text: 'Update Admin',
                    submit_method: 'PATCH' %>

app/views/admins/edit.html.erb
<h1>Edit admin</h1>

<%= render 'form', admin: @admin %>

app/views/admins/index.html.erb
<div class="page-header">
  <h1 class="page-title">Admins</h1>
  <nav class="page-nav">
    <div class="dropdown">
      <%= link_to "Add new Admin",
                  new_email_authentication_invitation_path,
                  class: "btn btn-sm btn-primary" %>
    </div>
  </nav>
</div>

<% @admins.each do |admin| %>
  <div class="card" title="<%= admin.email %>">
    <div class="row">
      <div class="col col-md-6">
        <h5>
          <%= link_to admin.email, admin_path(admin) %>
        </h5>
        <div class="mt-2"><i class="fas fa-shield-alt light mr-2"></i> <%= admin.role %></div>
      </div>
      <div class="col-md-6 text-right">
        <% if admin.invited_to_sign_up? %>
          <span class="badge badge-success badge-pill mr-4 mt-1" style="font-size: 90%; font-weight: normal;">Invite sent</span>
        <% end %>

        <% if policy([:manage, :admin, admin]).edit? %>
          <%= link_to 'Edit', edit_admin_path(admin), class: "btn btn-sm btn-outline-primary" %>
        <% end %>

        <% if policy([:manage, :admin, admin]).destroy? %>
          <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, admin_path(admin), method: :delete, data: { confirm: "Are you sure you want to delete #{admin.email}?" }, class: "btn btn-sm btn-outline-danger" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/admins/show.html.erb
<div class="page-header">
  <h1 class="page-title">
    <% if policy([:manage, :admin, User]).index? %>
      <%= link_to "Admins", admins_path, class: "#{active_controller?("email_authentications")}" %>
      <i class="fas fa-angle-right light"></i>
    <% end %>

    Admin
  </h1>
  <nav class="page-nav">
    <% if policy([:manage, :admin, @admin]).edit? %>
      <%= link_to 'Edit admin', edit_admin_path(@admin), class: "btn btn-sm btn-primary" %>
    <% end %>
  </nav>
</div>

<div class="card">
  <h2>
    <%= @admin.full_name %>
  </h2>
  <div class="card-row">
    <h5><i class="fas fa-envelope"></i> Email: <%= mail_to @admin.email %></h5>
    <h5><i class="fas fa-shield-alt"></i> Role: <%= @admin.role %></h5>
    <h5><i class="fas fa-lock"></i> Permissions:</h5>
    <ul>
      <% @admin.user_permissions.group_by(&:permission_slug).each do |permission_slug, user_permissions| %>
        <li><%= permission_slug.titleize %></li>
        <ul>
          <% user_permissions.each do |user_permission| %>
            <% if user_permission.resource.present? %>
              <li><%= link_to user_permission.resource.name, [:admin, user_permission.resource] %></li>
            <% end %>
          <% end %>
        </ul>
      <% end %>
    </ul>
  </div>
</div>