config/routes.rb
Rails.application.routes.draw do
  devise_scope :email_authentication do
    authenticated :email_authentication do
      root to: "admin#root"
    end

    unauthenticated :email_authentication do
      root to: "devise/sessions#new"
    end
  end

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  concern :sync_routes do
    scope '/patients' do
      get 'sync', to: 'patients#sync_to_user'
      post 'sync', to: 'patients#sync_from_user'
    end

    scope '/blood_pressures' do
      get 'sync', to: 'blood_pressures#sync_to_user'
      post 'sync', to: 'blood_pressures#sync_from_user'
    end

    scope '/blood_sugars' do
      get 'sync', to: 'blood_sugars#sync_to_user'
      post 'sync', to: 'blood_sugars#sync_from_user'
    end

    scope '/prescription_drugs' do
      get 'sync', to: 'prescription_drugs#sync_to_user'
      post 'sync', to: 'prescription_drugs#sync_from_user'
    end

    scope '/facilities' do
      get 'sync', to: 'facilities#sync_to_user'
    end

    scope '/protocols' do
      get 'sync', to: 'protocols#sync_to_user'
    end

    scope '/appointments' do
      get 'sync', to: 'appointments#sync_to_user'
      post 'sync', to: 'appointments#sync_from_user'
    end

    scope '/medical_histories' do
      get 'sync', to: 'medical_histories#sync_to_user'
      post 'sync', to: 'medical_histories#sync_from_user'
    end
  end

  namespace :api, defaults: { format: 'json' } do
    get 'manifest.json', to: 'manifests#show'

    # Returning HTTP Status `410` for deprecated API version `v1`
    namespace :v1 do
      match '*all', via: [:get, :post, :put, :delete, :patch], to: proc { [410, {}, ['']] }
    end

    namespace :v2 do
      get 'ping', to: 'pings#show'
      post 'login', to: 'logins#login_user'

      # Exotel requires all endpoints to be GET
      scope :exotel_call_sessions do
        get 'fetch', to: 'exotel_call_sessions#fetch'
        get 'create', to: 'exotel_call_sessions#create'
        get 'terminate', to: 'exotel_call_sessions#terminate'
      end

      scope :users do
        get 'find', to: 'users#find'
        post 'register', to: 'users#register'
        post '/:id/request_otp', to: 'users#request_otp'
        post '/me/reset_password', to: 'users#reset_password'
      end

      scope '/communications' do
        get 'sync', to: 'communications#sync_to_user'
        post 'sync', to: 'communications#sync_from_user'
      end

      concerns :sync_routes

      resource :help, only: [:show], controller: "help"

      namespace :analytics do
        resource :user_analytics, only: [:show]
      end
    end

    namespace :current, path: 'v3' do
      get 'ping', to: 'pings#show'
      post 'login', to: 'logins#login_user'

      # Exotel requires all endpoints to be GET
      scope :exotel_call_sessions do
        get 'fetch', to: 'exotel_call_sessions#fetch'
        get 'create', to: 'exotel_call_sessions#create'
        get 'terminate', to: 'exotel_call_sessions#terminate'
      end

      resource :twilio_sms_delivery, only: [:create], controller: :twilio_sms_delivery

      scope :users do
        get 'find', to: 'users#find'
        post 'register', to: 'users#register'
        post '/:id/request_otp', to: 'users#request_otp'
        post '/me/reset_password', to: 'users#reset_password'
      end

      concerns :sync_routes

      scope '/encounters' do
        get 'sync', to: 'encounters#sync_to_user'
        post 'sync', to: 'encounters#sync_from_user'

        if FeatureToggle.enabled?('GENERATE_ENCOUNTER_ID_ENDPOINT')
          get 'generate_id', to: 'encounters#generate_id'
        end
      end

      resource :help, only: [:show], controller: "help"

      namespace :analytics do
        resource :user_analytics, only: [:show]
      end
    end
  end

  devise_for :email_authentications,
             path: 'email_authentications',
             controllers: { invitations: 'email_authentications/invitations' }

  resources :admins

  namespace :analytics do
    resources :facilities, only: [:show] do
      get 'graphics', to: 'facilities#whatsapp_graphics'
      get 'patient_list', to: 'facilities#patient_list'
      get 'share', to: 'facilities#share_anonymized_data'
    end

    resources :organizations do
      resources :districts, only: [:show] do
        get 'graphics', to: 'districts#whatsapp_graphics'
        get 'patient_list', to: 'districts#patient_list'
        get 'share', to: 'districts#share_anonymized_data'
      end
    end
  end

  resources :appointments, only: [:index, :update]
  resources :patients, only: [:index, :update]
  resources :organizations, only: [:index], path: 'dashboard'

  scope :my_facilities do
    get '/', to: 'my_facilities#index', as: 'my_facilities_overview'
    get 'ranked_facilities', to: 'my_facilities#ranked_facilities', as: 'my_facilities_ranked_facilities'
    get 'blood_pressure_control', to: 'my_facilities#blood_pressure_control', as: 'my_facilities_blood_pressure_control'
  end

  namespace :admin do
    resources :organizations

    resources :facilities, only: [:index] do
      collection do
        get 'upload'
        post 'upload'
      end
    end
    resources :facility_groups do
      resources :facilities
    end

    resources :protocols do
      resources :protocol_drugs
    end

    resources :users do
      put 'reset_otp', to: 'users#reset_otp'
      put 'disable_access', to: 'users#disable_access'
      put 'enable_access', to: 'users#enable_access'
    end
  end

  if FeatureToggle.enabled?('PURGE_ENDPOINT_FOR_QA')
    namespace :qa do
      delete 'purge', to: 'purges#purge_patient_data'
    end
  end

  authenticate :email_authentication, -> (a) { a.user.has_permission?(:view_sidekiq_ui) } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_analytics_table.html.erb
<div class="card pr-0 pr-md-3">
  <div class="table-responsive table-compact">
    <table id="analytics-table">
      <colgroup>
        <col>
        <col style="border-left: 1px solid #dce4e8;">
        <col style="border-left: 1px solid #dce4e8;">
        <col>
        <col>
        <col style="border-left: 1px solid #dce4e8;">
        <col>
        <col>
        <col style="border-left: 1px solid #dce4e8;">
        <col>
        <col>
      </colgroup>
      <thead>
      <tr>
        <th><h3 class="ml-n2"><%= row_resource_description %></h3></th>
        <th class="row-label"><strong>Registered patients</strong></th>
        <th class="row-label" colspan="3"><strong>Follow-up patients</strong></th>
        <th class="row-label" colspan="3"><strong>New registrations</strong></th>
        <th class="row-label" colspan="3"><strong>Patients called</strong></th>
      </tr>

      <tr data-sort-method="thead">
        <th class="row-label sort-label" style="text-align: left; padding: 8px 4px;" data-sort-default>Name</th>
        <!--Registered patients-->
        <th class="row-label sort-label" style="padding: 8px 4px;" data-sort-method="number">Total</th>

        <!--Follow-up patients-->
        <% dates_for_periods(@period, 3, include_current_period: @show_current_period).each do |date| %>
          <th class="row-label sort-label" style="padding: 8px 4px;" data-sort-method="number">
            <%= format_period(@period, date) %>
          </th>
        <% end %>

        <!--New registrations-->
        <% dates_for_periods(@period, 3, include_current_period: @show_current_period).each do |date| %>
          <th class="row-label sort-label" style="padding: 8px 4px;" data-sort-method="number">
            <%= format_period(@period, date) %>
          </th>
        <% end %>

        <!--Calls made -->
        <% dates_for_periods(@period, 3, include_current_period: @show_current_period).each do |date| %>
          <th class="row-label sort-label" style="padding: 8px 4px;" data-sort-method="number">
            <%= format_period(@period, date) %>
          </th>
        <% end %>
      </tr>

      </thead>
      <tbody>

      <tr class="row-total" data-sort-method="none">
        <td class="row-title row-total">All</td>

        <!--Registered patients-->
        <td class="row-total" style="text-align: center;">
          <%= dash_if_zero(dashboard_analytics.sum { |_, row| row[:total_registered_patients] || 0 }) %>
        </td>

        <!--Follow-up patients-->
        <% dates_for_periods(@period, 3, include_current_period: @show_current_period).each do |date| %>
          <td class="row-total" style="text-align: center;">
            <%= dash_if_zero(analytics_totals(dashboard_analytics, :follow_up_patients_by_period, date)) %>
          </td>
        <% end %>

        <!--New registrations-->
        <% dates_for_periods(@period, 3, include_current_period: @show_current_period).each do |date| %>
          <td class="row-total" style="text-align: center;">
            <%= dash_if_zero(analytics_totals(dashboard_analytics, :registered_patients_by_period, date)) %>
          </td>
        <% end %>

        <!--Calls made -->
        <% dates_for_periods(@period, 3, include_current_period: @show_current_period).each do |date| %>
          <td class="row-total" style="text-align: center;">
            <%= dash_if_zero(analytics_totals(dashboard_analytics, :total_calls_made_by_period, date)) %>
          </td>
        <% end %>
      </tr>

      <% policy_scope([:cohort_report, row_resource]).each do |resource| %>
        <% if dashboard_analytics[resource.id].present? %>
          <tr>
            <td class="row-title">
              <% if row_resource_link == :analytics_facility_path %>
                <%= link_to resource.send(row_resource_display_field),
                            send(row_resource_link, resource, period: @period) %>
              <% else %>
                <%= link_to resource.send(row_resource_display_field), send(row_resource_link, resource) %>
              <% end %>
            </td>

            <!--Registered patients-->
            <td style="text-align: center;">
              <%= dash_if_zero(dashboard_analytics.dig(resource.id, :total_registered_patients)) %>
            </td>

            <!--Follow-up patients-->
            <% dates_for_periods(@period, 3, include_current_period: @show_current_period).each do |date| %>
              <td style="text-align: center;">
                <%= dash_if_zero(dashboard_analytics.dig(resource.id, :follow_up_patients_by_period, date)) %>
              </td>
            <% end %>

            <!--New registrations-->
            <% dates_for_periods(@period, 3, include_current_period: @show_current_period).each do |date| %>
              <td style="text-align: center;">
                <%= dash_if_zero(dashboard_analytics.dig(resource.id, :registered_patients_by_period, date)) %>
              </td>
            <% end %>

            <!--Calls made -->
            <% dates_for_periods(@period, 3, include_current_period: @show_current_period).each do |date| %>
              <td style="text-align: center;">
                <%= dash_if_zero(dashboard_analytics.dig(resource.id, :total_calls_made_by_period, date)) %>
              </td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_cohort_charts.html.erb
<div class="card pb-4">
  <div class="row">
      <div class="col-lg-3">
            <h3>Cohort report</h3>
      </div>
      <div class="desc col-lg-9">
        <div class="key desktop">
          <div class="key-definition didntattend">Didn't attend for<br class="mobile"> follow-up visit</div>
          &nbsp;
          <div class="key-definition uncontrolled">Visited and <br class="mobile">BP &ge;&nbsp;140/90</div>
          &nbsp;
          <div class="key-definition controlled">Visited and <br class="mobile">BP &lt;&nbsp;140/90</div>
        </div>
      </div>
  </div>

  <% cohort_analytics.each_with_index do |(report_dates, analytics), index| %>
    <%
      cohort_start, report_start = report_dates

      registered = analytics[:registered]
      followed_up = analytics[:followed_up]
      defaulted = analytics[:defaulted]
      controlled = analytics[:controlled]
      uncontrolled = analytics[:uncontrolled]

      if @period == :quarter
        report_period = quarter_string(report_start)
        cohort_period = quarter_string(cohort_start)
      else
        report_period = [report_start.strftime("%b"), (report_start + 1.month).end_of_month.strftime("%b")].join("/")
        cohort_period = cohort_start.strftime("%b-%Y")
      end
    %>

    <div class="split-row">
      <div class="row px-lg-0">
        <div class="col-lg-3 nowrap order-lg-1">
          <h6><%= registered %> patients registered in <%= "#{cohort_period}" %></h6>
          <div class="small light">Result from last visit in <%= report_period %></div>
        </div>
        <div class="col-lg-9 order-lg-2">
          <table class="split-bars">
            <tr>
              <% if registered > 0 %>
                <%
                  controlled_percent = (controlled.to_f / registered * 100).round
                  uncontrolled_percent = (uncontrolled.to_f / registered * 100).round
                  default_percent = (defaulted.to_f / registered * 100).round
                %>

                <td class="bar bar-1" data-toggle="tooltip" data-placement="top" data-trigger="hover focus click" title="<%= (defaulted > 0 && default_percent == 0) ? "< 1" : default_percent %>% didn't attend" style="width: <%= default_percent %>%;"><%= defaulted %></td>
                <td class="bar bar-2" data-toggle="tooltip" data-placement="top" data-trigger="hover focus click" title="<%= (uncontrolled > 0 && uncontrolled_percent == 0) ? "< 1" : uncontrolled_percent %>% visited and uncontrolled" style="width: <%= uncontrolled_percent %>%;"><%= uncontrolled %></td>
                <td class="bar bar-3" data-toggle="tooltip" data-placement="top" data-trigger="hover focus click" title="<%= (controlled > 0 && controlled_percent == 0) ? "< 1" : controlled_percent %>% visited and controlled" style="width: <%= controlled_percent %>%;"><%= controlled %></td>
              <% else %>
                <td class="bar bar-1 bar-none" style="width: 100%;">No patients</td>
              <% end %>
            </tr>
          </table>
        </div>
      </div>
    </div>
  <% end %>

  <div class="key mobile">
    <div class="row">
      <div class="col-4 key-definition didntattend">Didn't attend for follow-up visit</div>
      <div class="col-4 key-definition uncontrolled">Visited and BP &ge;&nbsp;140/90</div>
      <div class="col-4 key-definition controlled">Visited and BP &lt;&nbsp;140/90</div>
    </div>
  </div>
</div>

app/views/shared/_followup_patient_card.html.erb
<div class="card">
    
    <h5 class="mb-2">
        <%= patient.full_name %>,
        <%= patient.gender.capitalize %>,
        <%= patient.current_age %>
    </h5>

    <div>
      <% if show_registration_date %>
        <div>
          <span class="text-secondary">Registered on:</span>
          <%= patient.registration_date %><br>
        </div>
      <% end %>
      <% if bp = patient.latest_blood_pressure %>
        <div>
          <span class="text-secondary">Last BP:</span>
          <%= bp.to_s %> recorded at <%= bp.facility.name %>
          <%= rounded_time_ago_in_words(bp.device_created_at.to_date) %>
        </div>
      <% end %>
      <div>
        <span class="text-secondary">Home:</span>
        <% if patient.address.has_street_address? %><%= patient.address.street_address %>,<% end %>
        <%= patient.address.village_or_colony %>
      </div>
    </div>
            
    <% if days_overdue.present? %>
        <div class="card-date">
            <% if high_risk %>
            <div>
              <span class="badge badge-pill badge-danger ml-2">HIGH RISK</span>
            </div>
            <% end %>
            <%= days_overdue %> days overdue
        </div>
    <% end %>  
    
    <div class="row mt-2">
        <div class="col-md-3 mt-2">
            <% if phone_number = patient.phone_numbers.first&.number %>
                <a href="tel:<%= phone_number %>" class="btn btn-sm btn-block btn-phone btn-outline-primary btn-phone"><i class="fas fa-phone" style="font-size: 80%;"></i> <%= phone_number %></a>
            <% else %>
                <a href="#" class="btn btn-sm btn-block btn-info disabled">&lt; No mobile &gt;</a>
            <% end %>
        </div>
        <div class="col-md-4 mt-2">
            <%= bootstrap_form_with(model: form_model) do |form| %>
                <%= form.hidden_field :selected_facility_id, value: @facility_id %>
                <%= form.hidden_field :page, value: @page %>
                <%= form.select :call_result,
                    call_result_options,
                    {
                        prompt: "Result of follow-up...",
                        hide_label: true
                    },
                    onchange: "this.form.submit();",
                    class: "form-control-sm"
            %>
            <% end %>
        </div>
    </div>
    <% last_interaction = show_last_interaction_date_and_result(patient) %>
        <% if last_interaction.present? %>
            <div class="card-footer text-info">
                Last interaction: <%= last_interaction %>
            </div>
        <% end %>

</div>

app/views/shared/_graph.html.erb
<div class="featured-graph" style="text-align: center;">
  <table>
    <tr>
      <% max_value = graph_data.values.max %>
      <% graph_data.each do |key, value| %>
        <td>
          <%= content_tag 'div', value,
                          options.merge(class: "featured-graph-column #{column_class}",
                                        style: column_height_styles(value, max_value: max_value, max_height: 50)) %>
          <span class="featured-month"><%= key %></span>
        </td>
      <% end %>
    </tr>
  </table>
</div>

app/views/shared/_icon_whatsapp_icon.html.erb
<svg version="1.1" id="whatsapp-logo-notext" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 39 39" style="enable-background:new 0 0 39 39;" xml:space="preserve"><style type="text/css">
    .logo_white{fill:#FFFFFF;}
    .logo_green{fill:#00E676;}
</style><path class="logo_green" d="M10.7,32.8l0.6,0.3c2.5,1.5,5.3,2.2,8.1,2.2l0,0c8.8,0,16-7.2,16-16c0-4.2-1.7-8.3-4.7-11.3&#10;                            s-7-4.7-11.3-4.7c-8.8,0-16,7.2-15.9,16.1c0,3,0.9,5.9,2.4,8.4l0.4,0.6l-1.6,5.9L10.7,32.8z"/><path class="logo_white" d="M32.4,6.4C29,2.9,24.3,1,19.5,1C9.3,1,1.1,9.3,1.2,19.4c0,3.2,0.9,6.3,2.4,9.1L1,38l9.7-2.5&#10;                            c2.7,1.5,5.7,2.2,8.7,2.2l0,0c10.1,0,18.3-8.3,18.3-18.4C37.7,14.4,35.8,9.8,32.4,6.4z M19.5,34.6L19.5,34.6c-2.7,0-5.4-0.7-7.7-2.1&#10;                            l-0.6-0.3l-5.8,1.5L6.9,28l-0.4-0.6c-4.4-7.1-2.3-16.5,4.9-20.9s16.5-2.3,20.9,4.9s2.3,16.5-4.9,20.9C25.1,33.8,22.3,34.6,19.5,34.6&#10;                            z M28.3,23.5L27.2,23c0,0-1.6-0.7-2.6-1.2c-0.1,0-0.2-0.1-0.3-0.1c-0.3,0-0.5,0.1-0.7,0.2l0,0c0,0-0.1,0.1-1.5,1.7&#10;                            c-0.1,0.2-0.3,0.3-0.5,0.3h-0.1c-0.1,0-0.3-0.1-0.4-0.2l-0.5-0.2l0,0c-1.1-0.5-2.1-1.1-2.9-1.9c-0.2-0.2-0.5-0.4-0.7-0.6&#10;                            c-0.7-0.7-1.4-1.5-1.9-2.4L15,18.4c-0.1-0.1-0.1-0.2-0.2-0.4c0-0.2,0-0.4,0.1-0.5c0,0,0.4-0.5,0.7-0.8c0.2-0.2,0.3-0.5,0.5-0.7&#10;                            c0.2-0.3,0.3-0.7,0.2-1c-0.1-0.5-1.3-3.2-1.6-3.8c-0.2-0.3-0.4-0.4-0.7-0.5h-0.3c-0.2,0-0.5,0-0.8,0c-0.2,0-0.4,0.1-0.6,0.1&#10;                            l-0.1,0.1c-0.2,0.1-0.4,0.3-0.6,0.4c-0.2,0.2-0.3,0.4-0.5,0.6c-0.7,0.9-1.1,2-1.1,3.1l0,0c0,0.8,0.2,1.6,0.5,2.3l0.1,0.3&#10;                            c0.9,1.9,2.1,3.6,3.7,5.1l0.4,0.4c0.3,0.3,0.6,0.5,0.8,0.8c2.1,1.8,4.5,3.1,7.2,3.8c0.3,0.1,0.7,0.1,1,0.2l0,0c0.3,0,0.7,0,1,0&#10;                            c0.5,0,1.1-0.2,1.5-0.4c0.3-0.2,0.5-0.2,0.7-0.4l0.2-0.2c0.2-0.2,0.4-0.3,0.6-0.5s0.4-0.4,0.5-0.6c0.2-0.4,0.3-0.9,0.4-1.4&#10;                            c0-0.2,0-0.5,0-0.7C28.6,23.7,28.5,23.6,28.3,23.5z"/></svg> 

app/views/shared/_paginate_and_filter_by_district.html.erb
<%= bootstrap_form_with(url: form_url, method: :get, layout: :horizontal, class: "mt-4") do |form| %>
  <div class="form-row">
    <div id="district-selector" class="form-group col-md-6">
      <%= form.select :district,
                      policy_scope(scope_namespace).sort_by(&:district).map { |facility| [facility.district, facility.district] }.uniq,
                      {
                          hide_label: true,
                          include_blank: "All districts",
                          selected: district,
                          wrapper: false
                      },
                      onchange: "this.form.submit();"
      %>
    </div>
    <div id="limit-selector" class="form-group col-md-3">
      <%= form.select :per_page,
                      ["20 per page", "50 per page"],
                      {
                          hide_label: true,
                          selected: per_page,
                      },
                      onchange: "this.form.submit();"
      %>
    </div>
  </div>
  <%= form.submit "Filter", style: "position: absolute; left: -9999px; width: 1px; height: 1px;" %>
<% end %>

app/views/shared/_recent_bp_log.html.erb
<div class="card" id="recent-bps">
  <h3>Recent BPs</h3>
  <p> A log of the BPs recorded
    <% if display_model == :facility %>
      at this facility.
    <% elsif display_model == :user %>
      by this user.
    <% end %></p>
  <% if blood_pressures.any? %>
    <div class="table-responsive table-compact pb-3">
      <table>
        <colgroup>
          <col>
          <col>
          <col>
          <col>
          <col class="table-divider">
        </colgroup>
        <thead>
        <tr>
          <th colspan="4"></th>
          <% if display_model == :facility %>
            <th class="pl-1 pb-3">Recorded by</th>
          <% end %>
          <% if display_model == :user %>
            <th class="pl-1 pb-3">Facility</th>
          <% end %>
        </tr>
        </thead>
        <% last_date = nil %>
        <% blood_pressures.each do |bp| %>
          <% next if bp.patient.blank? %>
          <% if print_date = (bp.recorded_at.to_date != last_date) %>
            <% last_date = bp.recorded_at.to_date %>
          <% end %>
          <tr class="<%= "date-row" if print_date %>">
            <td class="nowrap" style="width: 10em; <%= "border: none;" if !print_date %>">
              <% if print_date %>
                <strong>
                  <%= l bp.recorded_at.to_date %>
                </strong>
              <% end %>
            </td>
            <td class="nowrap text-muted"><%= bp.recorded_at.strftime("%I:%M %p") %></td>
            <td class="nowrap <%= bp.hypertensive? ? "bp-uncontrolled" : "bp-controlled text-muted" %>">
              <i class="fas fa-heart mr-2"></i> <%= bp.to_s %></td>
            <td class="nowrap">
              <% if bp.recorded_at.to_date > bp.patient.recorded_at.to_date %>
                <span class="patient-return text-muted">Follow-up patient</span>
              <% else %>
                <span class="patient-new">New registration</span>
              <% end %>
            </td>
            <% if display_model == :facility %>
              <td class="nowrap"><%= bp.user.present? ? link_to(bp.user.full_name, [:admin, bp.user]) : "unknown" %></td>
            <% end %>
            <% if display_model == :user %>
              <td class="nowrap"><%= bp.facility.present? ? link_to(bp.facility.name, analytics_facility_path(bp.facility)) : "unknown" %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  <% else %>
    <p class="text-muted mb-0">
      <i class="fas fa-chevron-left"></i>
      No BPs recorded
      <i class="fas fa-chevron-right"></i>
    </p>
  <% end %>
  <div>
    <%= paginate blood_pressures, params: { anchor: 'recent-bps' } %>
  </div>
</div>

app/views/shared/_user_approvals.html.erb
<% if @users_requesting_approval.any? && policy([:manage, :user, @users_requesting_approval.first]).enable_access? %>
  <% if @users_requesting_approval.any? %>
    <h2>Users to review</h2>
    <p>Contact these users promptly. Check that they are approved to access patient data at their facility.</p>

    <% @users_requesting_approval.each do |user| %>
      <% if policy([:manage, :user, user]).enable_access? %>
          <div class="user-row">
                <h5><%= link_to user.full_name, [:admin, user] %></h5>
                <div class="text-grey mt-1 mb-2">
                    <% if user.sync_approval_status_reason.present? %>
                      <span><%= user.sync_approval_status_reason %> at <%= user.registration_facility.present? ? link_to(user.registration_facility.name, admin_facilities_path(user.registration_facility)) : "N/A" %></span>, <%= l user.updated_at.to_date %>
                    <% end %>
                </div>

              <div class="row">
                  <div class="col">
                      <a href="tel:<%= user.phone_number %>" class="btn btn-outline-primary btn-sm btn-phone" style="letter-spacing: 0.1em;"><i class="fas fa-phone" style="font-size: 90%;"></i> <%= user.phone_number %></a>
                  </div>
                  <div class="col text-right">

                    <%= link_to "Allow access", admin_user_enable_access_path(user), method: :put, class: "btn btn-sm btn-outline-success", data: { confirm: I18n.t('admin.enable_access_alert') } %>
                    <%= link_to '<i class="fas fa-times"></i>'.html_safe, '#deny-access-modal-' + user.id, 'data-toggle' => 'modal', class: "btn btn-sm btn-outline-danger" %>

                    <%= render partial: "admin/users/deny_access_modal", locals: { user: user } %>
                  </div>
            </div>
          </div>
      <% end %>
    <% end %>
  <% else %>
      <h2>All users reviewed</h2>
      <p><i class="fas fa-check"></i> All user approvals are complete. Nice work.</p>
  <% end %>

  <%= paginate @users_requesting_approval %>
<% else %>
    <h2>All users reviewed</h2>
    <p><i class="fas fa-check"></i> All user approvals are complete. Nice work.</p>
<% end %>