config/routes.rb
Rails.application.routes.draw do
  devise_scope :email_authentication do
    authenticated :email_authentication do
      root to: "admin#root"
    end

    unauthenticated :email_authentication do
      root to: "devise/sessions#new"
    end
  end

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  concern :sync_routes do
    scope '/patients' do
      get 'sync', to: 'patients#sync_to_user'
      post 'sync', to: 'patients#sync_from_user'
    end

    scope '/blood_pressures' do
      get 'sync', to: 'blood_pressures#sync_to_user'
      post 'sync', to: 'blood_pressures#sync_from_user'
    end

    scope '/blood_sugars' do
      get 'sync', to: 'blood_sugars#sync_to_user'
      post 'sync', to: 'blood_sugars#sync_from_user'
    end

    scope '/prescription_drugs' do
      get 'sync', to: 'prescription_drugs#sync_to_user'
      post 'sync', to: 'prescription_drugs#sync_from_user'
    end

    scope '/facilities' do
      get 'sync', to: 'facilities#sync_to_user'
    end

    scope '/protocols' do
      get 'sync', to: 'protocols#sync_to_user'
    end

    scope '/appointments' do
      get 'sync', to: 'appointments#sync_to_user'
      post 'sync', to: 'appointments#sync_from_user'
    end

    scope '/medical_histories' do
      get 'sync', to: 'medical_histories#sync_to_user'
      post 'sync', to: 'medical_histories#sync_from_user'
    end
  end

  namespace :api, defaults: { format: 'json' } do
    get 'manifest.json', to: 'manifests#show'

    # Returning HTTP Status `410` for deprecated API version `v1`
    namespace :v1 do
      match '*all', via: [:get, :post, :put, :delete, :patch], to: proc { [410, {}, ['']] }
    end

    namespace :v2 do
      get 'ping', to: 'pings#show'
      post 'login', to: 'logins#login_user'

      # Exotel requires all endpoints to be GET
      scope :exotel_call_sessions do
        get 'fetch', to: 'exotel_call_sessions#fetch'
        get 'create', to: 'exotel_call_sessions#create'
        get 'terminate', to: 'exotel_call_sessions#terminate'
      end

      scope :users do
        get 'find', to: 'users#find'
        post 'register', to: 'users#register'
        post '/:id/request_otp', to: 'users#request_otp'
        post '/me/reset_password', to: 'users#reset_password'
      end

      scope '/communications' do
        get 'sync', to: 'communications#sync_to_user'
        post 'sync', to: 'communications#sync_from_user'
      end

      concerns :sync_routes

      resource :help, only: [:show], controller: "help"

      namespace :analytics do
        resource :user_analytics, only: [:show]
      end
    end

    namespace :current, path: 'v3' do
      get 'ping', to: 'pings#show'
      post 'login', to: 'logins#login_user'

      # Exotel requires all endpoints to be GET
      scope :exotel_call_sessions do
        get 'fetch', to: 'exotel_call_sessions#fetch'
        get 'create', to: 'exotel_call_sessions#create'
        get 'terminate', to: 'exotel_call_sessions#terminate'
      end

      resource :twilio_sms_delivery, only: [:create], controller: :twilio_sms_delivery

      scope :users do
        get 'find', to: 'users#find'
        post 'register', to: 'users#register'
        post '/:id/request_otp', to: 'users#request_otp'
        post '/me/reset_password', to: 'users#reset_password'
      end

      concerns :sync_routes

      scope '/encounters' do
        get 'sync', to: 'encounters#sync_to_user'
        post 'sync', to: 'encounters#sync_from_user'

        if FeatureToggle.enabled?('GENERATE_ENCOUNTER_ID_ENDPOINT')
          get 'generate_id', to: 'encounters#generate_id'
        end
      end

      resource :help, only: [:show], controller: "help"

      namespace :analytics do
        resource :user_analytics, only: [:show]
      end
    end
  end

  devise_for :email_authentications,
             path: 'email_authentications',
             controllers: { invitations: 'email_authentications/invitations' }

  resources :admins

  namespace :analytics do
    resources :facilities, only: [:show] do
      get 'graphics', to: 'facilities#whatsapp_graphics'
      get 'patient_list', to: 'facilities#patient_list'
      get 'share', to: 'facilities#share_anonymized_data'
    end

    resources :organizations do
      resources :districts, only: [:show] do
        get 'graphics', to: 'districts#whatsapp_graphics'
        get 'patient_list', to: 'districts#patient_list'
        get 'share', to: 'districts#share_anonymized_data'
      end
    end
  end

  resources :appointments, only: [:index, :update]
  resources :patients, only: [:index, :update]
  resources :organizations, only: [:index], path: 'dashboard'

  scope :my_facilities do
    get '/', to: 'my_facilities#index', as: 'my_facilities_overview'
    get 'ranked_facilities', to: 'my_facilities#ranked_facilities', as: 'my_facilities_ranked_facilities'
    get 'blood_pressure_control', to: 'my_facilities#blood_pressure_control', as: 'my_facilities_blood_pressure_control'
  end

  namespace :admin do
    resources :organizations

    resources :facilities, only: [:index] do
      collection do
        get 'upload'
        post 'upload'
      end
    end
    resources :facility_groups do
      resources :facilities
    end

    resources :protocols do
      resources :protocol_drugs
    end

    resources :users do
      put 'reset_otp', to: 'users#reset_otp'
      put 'disable_access', to: 'users#disable_access'
      put 'enable_access', to: 'users#enable_access'
    end
  end

  if FeatureToggle.enabled?('PURGE_ENDPOINT_FOR_QA')
    namespace :qa do
      delete 'purge', to: 'purges#purge_patient_data'
    end
  end

  authenticate :email_authentication, -> (a) { a.user.has_permission?(:view_sidekiq_ui) } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/facility_group.rb
class FacilityGroup < ApplicationRecord
  extend FriendlyId
  default_scope -> { kept }

  belongs_to :organization
  belongs_to :protocol

  has_many :facilities, dependent: :nullify
  has_many :users, through: :facilities

  has_many :patients, through: :facilities, source: :registered_patients
  has_many :blood_pressures, through: :facilities
  has_many :blood_sugars, through:  :facilities
  has_many :encounters, through: :facilities
  has_many :prescription_drugs, through: :facilities
  has_many :appointments, through: :facilities

  has_many :medical_histories, through: :patients
  has_many :communications, through: :appointments

  validates :name, presence: true
  validates :organization, presence: true

  friendly_id :name, use: :slugged

  def report_on_patients
    Patient.where(registration_facility: facilities)
  end
end

app/controllers/admin/facility_groups_controller.rb
class Admin::FacilityGroupsController < AdminController
  before_action :set_facility_group, only: [:show, :edit, :update, :destroy]
  before_action :set_organizations, only: [:new, :edit]
  before_action :set_protocols, only: [:new, :edit]

  def index
    authorize([:manage, FacilityGroup])
    @facility_groups = policy_scope([:manage, FacilityGroup]).order(:name)
  end

  def show
    @facilities = @facility_group.facilities.order(:name)
    @users = @facility_group.users.order(:full_name)
  end

  def new
    @facility_group = FacilityGroup.new
    authorize([:manage, @facility_group])
  end

  def edit
  end

  def create
    @facility_group = FacilityGroup.new(facility_group_params)
    authorize([:manage, @facility_group])

    if @facility_group.save
      redirect_to admin_facilities_url, notice: 'FacilityGroup was successfully created.'
    else
      render :new
    end
  end

  def update
    if @facility_group.update(facility_group_params)
      redirect_to admin_facilities_url, notice: 'FacilityGroup was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @facility_group.discard
      redirect_to admin_facilities_url, notice: 'FacilityGroup was successfully deleted.'
    else
      redirect_to admin_facilities_url, alert: 'FacilityGroup could not be deleted'
    end
  end

  private

  def set_organizations
    @organizations = policy_scope([:manage, :facility, Organization])
  end

  def set_protocols
    @protocols = Protocol.all
  end

  def set_facility_group
    @facility_group = FacilityGroup.friendly.find(params[:id])
    authorize([:manage, @facility_group])
  end

  def facility_group_params
    params.require(:facility_group).permit(
      :organization_id,
      :name,
      :description,
      :protocol_id,
      facility_ids: []
    )
  end
end

app/views/admin/facility_groups/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= bootstrap_form_with(model: [:admin, facility_group], local: true, autocomplete: "off", label_errors: true) do |form| %>
      <%= form.select(:organization_id, organizations.map { |organization| [organization.name, organization.id]} ) %>

      <%= form.text_field :name, id: :facility_name, required: true, autocomplete: "off" %>
      <%= form.text_field :description, id: :facility_description, autocomplete: "off" %>

      <% if facility_group.facilities.present? %>
        <%= form.collection_check_boxes :facility_ids, facility_group.facilities, :id, :name, label: "Associated facilities", checked_value: 1 %>
      <% end %>

      <% if Facility.where(facility_group: nil).present? %>
        <%= form.collection_check_boxes :facility_ids, Facility.where(facility_group: nil), :id, :name, label: "Unassociated facilities", checked: true %>
      <% else %>
        <% if facility_group.new_record? %>
          <div class="row">
            <div class="col-md-9 mb-3 text-warning">All existing facilities belong to a facility group.</div>
            <!-- <div class="col-md-3 mb-3 text-warning">
              <%#= link_to 'New facility', new_admin_facility_path, class: "float-right btn btn-sm btn-primary" %>
            </div> -->
          </div>
        <% end %>
      <% end %>

      <%= form.select(:protocol_id, protocols.map { |protocol| [protocol.name, protocol.id]} ) %>

      <%= form.primary %>
    <% end %>
  </div>
</div>

app/views/admin/facility_groups/edit.html.erb
<div class="page-header">
  <h1 class="page-title">Edit facility group</h1>
  <nav class="page-nav">
    <% if policy([:manage, @facility_group]).destroy? %>
      <%= link_to 'Delete facility group', [:admin, @facility_group], method: :delete, data: { confirm: "Are you sure you want to delete #{@facility_group.name}?" }, class: "btn btn-outline-danger ml-4" %>
    <% end %>
  </nav>
</div>

<%= render 'form', facility_group: @facility_group, organizations: @organizations,protocols: @protocols %>

app/views/admin/facility_groups/index.html.erb
<h1>Facility Groups</h1>

<div class="top-buttons">
<% if policy([:manage, Organization]).new? %>
  <%= link_to 'New organization', new_admin_facility_path, class: "btn btn-sm btn-primary" %>
<% end %>
</div>


<table class="table-responsive table">
  <thead class="thead-light">
    <tr>
      <th>Description</th>
      <th>Facility Groups</th>
      <th>Facilities</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td class="nowrap"><%= link_to organization.name, [:admin, organization] %></td>
        <td><%= organization.description %></td>
        <td><%= organization.facility_groups.count %></td>
        <td><%= organization.facility_groups.flat_map(&:facilities).count %></td>
        <% if policy([:manage, organization]).edit? %>
          <td><%= link_to 'Edit', edit_admin_facility_path(organization) %></td>
        <% end %>
        <% if policy([:manage, organization]).destroy? %>
          <td><%= link_to 'Delete', [:admin, organization], method: :delete, data: { confirm: "Are you sure you want to delete #{organization.name}?" } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/facility_groups/new.html.erb
<h1>New facility group</h1>

<%= render 'form', facility_group: @facility_group, organizations: @organizations, protocols: @protocols %>

app/views/admin/facility_groups/show.html.erb
<div class="page-header">
  <h1 class="page-title">
    <small><%= @facility_group.organization.name %></small><br>
    <%= @facility_group.name %>
  </h1>
  <nav class="page-nav">
    <% if policy([:manage, @facility_group]).edit? %>
      <%= link_to 'Edit facility group', edit_admin_facility_group_path(@facility_group), class: "btn btn-sm btn-primary" %>
    <% end %>
  </nav>
</div>

<h2>Protocol</h2>
<p><%= link_to @facility_group.protocol.name, admin_protocol_path(@facility_group.protocol) %></p>

<h2>Facilities</h2>
<div class="table-responsive">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Village/colony</th>
        <th>District</th>
        <th>State</th>
        <th>Country</th>
        <th>Pin</th>
        <th>Facility&nbsp;type</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @facility_group.facilities.order(:name).each do |facility| %>
        <tr>
          <td class="nowrap"><%= link_to facility.name, [:admin, @facility_group, facility] %></td>
          <td><%= facility.street_address %></td>
          <td><%= facility.village_or_colony %></td>
          <td><%= facility.district %></td>
          <td><%= facility.state %></td>
          <td><%= facility.country %></td>
          <td><%= facility.pin %></td>
          <td><%= facility.facility_type %></td>
          <% if policy([:manage, :facility, facility]).edit? %>
            <td><%= link_to 'Edit', edit_admin_facility_group_facility_path(@facility_group, facility) %></td>
          <% end %>
          <% if policy([:manage, :facility, facility]).destroy? %>
            <td><%= link_to 'Delete', [:admin, @facility_group, facility], method: :delete, data: { confirm: "Are you sure you want to delete #{facility.name}?" } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>