config/routes.rb
Rails.application.routes.draw do
  devise_scope :email_authentication do
    authenticated :email_authentication do
      root to: "admin#root"
    end

    unauthenticated :email_authentication do
      root to: "devise/sessions#new"
    end
  end

  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  concern :sync_routes do
    scope '/patients' do
      get 'sync', to: 'patients#sync_to_user'
      post 'sync', to: 'patients#sync_from_user'
    end

    scope '/blood_pressures' do
      get 'sync', to: 'blood_pressures#sync_to_user'
      post 'sync', to: 'blood_pressures#sync_from_user'
    end

    scope '/blood_sugars' do
      get 'sync', to: 'blood_sugars#sync_to_user'
      post 'sync', to: 'blood_sugars#sync_from_user'
    end

    scope '/prescription_drugs' do
      get 'sync', to: 'prescription_drugs#sync_to_user'
      post 'sync', to: 'prescription_drugs#sync_from_user'
    end

    scope '/facilities' do
      get 'sync', to: 'facilities#sync_to_user'
    end

    scope '/protocols' do
      get 'sync', to: 'protocols#sync_to_user'
    end

    scope '/appointments' do
      get 'sync', to: 'appointments#sync_to_user'
      post 'sync', to: 'appointments#sync_from_user'
    end

    scope '/medical_histories' do
      get 'sync', to: 'medical_histories#sync_to_user'
      post 'sync', to: 'medical_histories#sync_from_user'
    end
  end

  namespace :api, defaults: { format: 'json' } do
    get 'manifest.json', to: 'manifests#show'

    # Returning HTTP Status `410` for deprecated API version `v1`
    namespace :v1 do
      match '*all', via: [:get, :post, :put, :delete, :patch], to: proc { [410, {}, ['']] }
    end

    namespace :v2 do
      get 'ping', to: 'pings#show'
      post 'login', to: 'logins#login_user'

      # Exotel requires all endpoints to be GET
      scope :exotel_call_sessions do
        get 'fetch', to: 'exotel_call_sessions#fetch'
        get 'create', to: 'exotel_call_sessions#create'
        get 'terminate', to: 'exotel_call_sessions#terminate'
      end

      scope :users do
        get 'find', to: 'users#find'
        post 'register', to: 'users#register'
        post '/:id/request_otp', to: 'users#request_otp'
        post '/me/reset_password', to: 'users#reset_password'
      end

      scope '/communications' do
        get 'sync', to: 'communications#sync_to_user'
        post 'sync', to: 'communications#sync_from_user'
      end

      concerns :sync_routes

      resource :help, only: [:show], controller: "help"

      namespace :analytics do
        resource :user_analytics, only: [:show]
      end
    end

    namespace :current, path: 'v3' do
      get 'ping', to: 'pings#show'
      post 'login', to: 'logins#login_user'

      # Exotel requires all endpoints to be GET
      scope :exotel_call_sessions do
        get 'fetch', to: 'exotel_call_sessions#fetch'
        get 'create', to: 'exotel_call_sessions#create'
        get 'terminate', to: 'exotel_call_sessions#terminate'
      end

      resource :twilio_sms_delivery, only: [:create], controller: :twilio_sms_delivery

      scope :users do
        get 'find', to: 'users#find'
        post 'register', to: 'users#register'
        post '/:id/request_otp', to: 'users#request_otp'
        post '/me/reset_password', to: 'users#reset_password'
      end

      concerns :sync_routes

      scope '/encounters' do
        get 'sync', to: 'encounters#sync_to_user'
        post 'sync', to: 'encounters#sync_from_user'

        if FeatureToggle.enabled?('GENERATE_ENCOUNTER_ID_ENDPOINT')
          get 'generate_id', to: 'encounters#generate_id'
        end
      end

      resource :help, only: [:show], controller: "help"

      namespace :analytics do
        resource :user_analytics, only: [:show]
      end
    end
  end

  devise_for :email_authentications,
             path: 'email_authentications',
             controllers: { invitations: 'email_authentications/invitations' }

  resources :admins

  namespace :analytics do
    resources :facilities, only: [:show] do
      get 'graphics', to: 'facilities#whatsapp_graphics'
      get 'patient_list', to: 'facilities#patient_list'
      get 'share', to: 'facilities#share_anonymized_data'
    end

    resources :organizations do
      resources :districts, only: [:show] do
        get 'graphics', to: 'districts#whatsapp_graphics'
        get 'patient_list', to: 'districts#patient_list'
        get 'share', to: 'districts#share_anonymized_data'
      end
    end
  end

  resources :appointments, only: [:index, :update]
  resources :patients, only: [:index, :update]
  resources :organizations, only: [:index], path: 'dashboard'

  scope :my_facilities do
    get '/', to: 'my_facilities#index', as: 'my_facilities_overview'
    get 'ranked_facilities', to: 'my_facilities#ranked_facilities', as: 'my_facilities_ranked_facilities'
    get 'blood_pressure_control', to: 'my_facilities#blood_pressure_control', as: 'my_facilities_blood_pressure_control'
  end

  namespace :admin do
    resources :organizations

    resources :facilities, only: [:index] do
      collection do
        get 'upload'
        post 'upload'
      end
    end
    resources :facility_groups do
      resources :facilities
    end

    resources :protocols do
      resources :protocol_drugs
    end

    resources :users do
      put 'reset_otp', to: 'users#reset_otp'
      put 'disable_access', to: 'users#disable_access'
      put 'enable_access', to: 'users#enable_access'
    end
  end

  if FeatureToggle.enabled?('PURGE_ENDPOINT_FOR_QA')
    namespace :qa do
      delete 'purge', to: 'purges#purge_patient_data'
    end
  end

  authenticate :email_authentication, -> (a) { a.user.has_permission?(:view_sidekiq_ui) } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  extend FriendlyId

  has_many :facility_groups, dependent: :destroy
  has_many :facilities, through: :facility_groups
  has_many :users
  has_many :protocols, through: :facility_groups

  validates :name, presence: true

  friendly_id :name, use: :slugged

  def districts
    facilities.select(:district).distinct.pluck(:district)
  end
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < AdminController
  before_action :set_organization, only: [:edit, :update, :destroy]

  def index
    authorize([:manage, Organization])
    @organizations = policy_scope([:manage, Organization]).order(:name)
  end

  def new
    @organization = Organization.new
    authorize([:manage, @organization])
  end

  def edit
  end

  def create
    @organization = Organization.new(organization_params)
    authorize([:manage, @organization])

    if @organization.save
      redirect_to admin_organizations_url, notice: 'Organization was successfully created.'
    else
      render :new
    end
  end

  def update
    if @organization.update(organization_params)
      redirect_to admin_organizations_url, notice: 'Organization was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @organization.destroy
    redirect_to admin_organizations_url, notice: 'Organization was successfully deleted.'
  end

  private

  def set_organization
    @organization = Organization.friendly.find(params[:id])
    authorize([:manage, @organization])
  end

  def organization_params
    params.require(:organization).permit(
      :name,
      :description
    )
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < AdminController
  include Pagination

  def index
    authorize(:dashboard, :show?)

    @users_requesting_approval = policy_scope([:manage, :user, User])
                                   .requested_sync_approval
                                   .order(updated_at: :desc)

    @users_requesting_approval = paginate(@users_requesting_approval)

    @organizations = policy_scope([:cohort_report, Organization]).order(:name)
  end
end

app/views/admin/organizations/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= bootstrap_form_with(model: [:admin, organization], local: true, autocomplete: "off", label_errors: true) do |organization_form| %>
      <%= organization_form.text_field :name, id: :organization_name, required: true, autocomplete: "off"%>
      <%= organization_form.text_field :description, id: :organization_description, autocomplete: "off"%>

      <%= organization_form.primary %>
    <% end %>
  </div>
</div>

app/views/admin/organizations/edit.html.erb
<h1>Edit organization</h1>

<%= render 'form', organization: @organization %>

app/views/admin/organizations/index.html.erb
<div class="page-header">
  <h1 class="page-title">Organizations</h1>
  <nav class="page-nav">
    <% if policy([:manage, Organization]).new? %>
      <%= link_to 'Add Organization', new_admin_organization_path, class: "btn btn-sm btn-primary" %>
    <% end %>
  </nav>
</div>

<% @organizations.each do |organization| %>
  <div class="card">
    <div class="row">
      <div class="col-10">
        <h5 class="mb-1">
          <% if policy([:manage, organization]).edit? %>
            <%= link_to organization.name, edit_admin_organization_path(organization) %>
          <% else %>
            <%= organization.name %>
          <% end %>
        </h5>
        <div class="desc"><%= organization.description %>.</div>
        <div class="text-secondary mt-2">
          <i class="fas fa-network-wired mr-1 light"></i>&nbsp;<%= organization.facility_groups.count %>&nbsp;facility
          groups
          <i class="fas fa-hospital mr-1 ml-2 light"></i>&nbsp;<%= organization.facilities.count %>&nbsp;facilities
          <i class="fas fa-user-friends mr-1 ml-2 light"></i>&nbsp;<%= organization.users.count %>&nbsp;users
        </div>
      </div>
      <div class="col-2 text-right">
        <% if policy([:manage, organization]).destroy? %>
          <%= link_to '<i class="fas fa-trash-alt"></i>'.html_safe, [:admin, organization], method: :delete, class: "btn btn-outline-danger btn-sm", data: { confirm: "Are you sure you want to delete #{organization.name}?" } %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
      

app/views/admin/organizations/new.html.erb
<h1>New organization</h1>

<%= render 'form', organization: @organization %>